source = LibreOJ_6000
aim = fuck
$(source) : $(source).cpp
	clear;g++ $(source).cpp -o $(aim) -g;./${aim} < input
.PHONY : o d i
o : 
	./$(aim) < input
d : 
	gdb $(aim)
i :
	vim $(source).cpp
e :
	./$(aim)

